### PR TITLE
Image orientation fix

### PR DESCRIPTION
**Pull request by BamX**
I've added orientation fixing method. Related to #130.

@ws233 could you provide image with wrong orientation that cause problems. I'll add it like test.

### CODE REVIEW

**Comment by ws233** [comment]
Feel free to rotate any test image by 90 degrees.

Is it possible to bypass image rotation step and create rotated Pix right from the source image?

I just consider real examples I have in my project. There are panoramic images of size about 2000x15000 or even bigger. That's mean 1 image takes about 120MB. If we use this rotation code, that means we waste 3 images. One is the source on. Second is the rotated one. Third is the Pix image. Totally that is 360MB. That's definitely will cause issues on some devices :(

**Comment by BamX** [comment]
That may be a problem for big images. Not sure how to create correct pix without additional orientation-fixed image.

By the way I can't reproduce your problem. This test passes anyway:
```
it(@"Should fix orientation", ^{
    UIImage *image = helper.image;
    UIImage *rotatedImage = [UIImage imageWithCGImage:image.CGImage
                                                scale:image.scale
                                          orientation:UIImageOrientationLeft];

    [[theValue(image.imageOrientation) shouldNot] equal:theValue(rotatedImage.imageOrientation)];

    [[theBlock(^{
        [helper recognizeImage];
    }) shouldNot] raise];

    NSString *recognizedText = helper.tesseract.recognizedText;
    [[recognizedText should] containString:@"1234567890"];

    UIImage *thresholdedImage = helper.tesseract.thresholdedImage;
    [[theValue(thresholdedImage.imageOrientation) should] equal:theValue(UIImageOrientationUp)];
});
```
May be I rotating image wrong?

**Comment by ws233** [comment]
I tried this test without your last totation changes with well_scaned_page and it fails here:
        [[recognizedText should] containString:@"1234567890"];

I've already written that it was my fault. That seems I used this property in a wrong way.

Regarding creating Pix.
As I understand we just need to change for loops order.
For example, if the image has left orientation.
That means the outer loop should go for column first. and the inner loop should go for row. since we need to change the rows and collumns of the image.
If, the image is upside down, we should traverse it backword from the bottom-right order till the top-left.
And so on for the right orientation.

**Comment by ws233** [comment]
We should mention that it obligatory to have osd.traineddata in the tessdata folder for this to work.
Actually, my issue was due to this.
I thought that's a language file, that's why didn't include it.
I think a lot of user will do the same mistake.

**Comment by ws233** [comment]
And there is an image, which causes the crash during getting an orientation.
The crash is due to iterator is NULL. (if osd presents)
http://www.filedropper.com/original
Also, if you rotate it 90 degrees and try to get an orientation you will get another crash in Pix creating.
And that's very strange, because if I change this image to the grayscale it crashes due to NULL iterator in both cases.

**Comment by BamX** [comment]
I'm not sure that I understand your last two comments. What are you mean about ```osd.traineddata```? How it related to the issue. And could you describe crash you get?

**Comment by ws233** [comment]
Let me start from the beginning.
I mentioned 2 issues in the related issue page.
1. Crash when the image is 90 degrees rotated. You asked me to share the image where I do recieve this issue. I've shared it in the previous message. So more detailed steps to reproduce the issue.

      G8Tesseract* tesseract = [[G8Tesseract alloc] initWithLanguage:@"rus+eng"
                                                        engineMode:G8OCREngineModeTesseractOnly];
      tesseract.image = /*that image from the previous message. rotated or not. both cases are considered*/ // crash happens here if image rotated right. more detailed it happens somewhere in pixForImage case 32.
      // no delegate here, since we don't do thresholding yet
      tesseract.pageSegmentationMode = G8PageSegmentationModeOSDOnly;
      G8Orientation textOrientation = tesseract.orientation; // crash happens here, if the image is not rotated. More detailed it crashes here     iterator->Orientation(&orientation, &direction, &order, &deskewAngle); case iterator==NULL. we need to add checking here. and add this case to unit tests.

2. analyzeLayout related question. I've told that's my fault. I didn't add osd.traineddata to my tessdata folder. I thought it's a language file and it's not necessary for me at all. But it is. It's necessary for OSD detection. That's unclear. For me at least. We should add this info to all 4 methods used analyzeLayout and ASD detection.

Sorry for my vroken English and let me know, if I couldn't explain this clear again :)

**Comment by BamX** [comment]
I think I've got it. I've told @kevincon that for usong OSD(for ```G8PageSegmentationModeOSDOnly``` and ```G8PageSegmentationModeAutoOSD``` modes) you should use ```osd.traineddata```. For the issues you mentioned that is the key. And that should be described in methods documentation.
To prevent this kind of crashes I'll add NULL check for iterator.

(My English is not so good too :)

**Comment by ws233** [comment]
Good! That will solve only the one issue.
But the second one, if the image is rotated 90 degrees?
Will we use that redrawing code? Is it not possible to create Pix from the source image without rotating it?

**Comment by BamX** [comment]
May be we could use CGAffineTransform for that? It would be more clear, but may be slower. I think ```pixForImage``` method is too slow now anyway and could be rewritten. We should look closer in it implementation and think how to produce pix data faster.

**Comment by ws233** [comment]
And one more thing. Since analyseLayout may fail we need to have unset value for orieantation, writingDirection, textlineOrder and even deskewAngle.
I mean the user has to have an ability to understand that all of this function did return the undefined value.
But I don't know how to specify that deskewAngle is wrong.

**Comment by ws233** [comment]
CGAffineTransform seems to be a good decision. It will make the whole procedure slowly, but not so much. Only on transformation oparator will be added to an operation of getting the every pixel.

Do you have any ideas how to improve this algorithm?
Perhaps, I can help with this.

**Comment by BamX** [comment]
I think we could fetch pixData from UIImage without copying it pixel by pixel. Let me work with it.

**Comment by ws233** [comment]
Ah! I see. Hope, you'll succeed.

**Comment by BamX** [comment]
I've found another way to create Pix. Everything work fine for existing tests. I'll add some tests with rotated image soon. I've added a test that doing image->pix->image conversion and check result image to be equal to the source image.

There was one broken test: SimpleImage_SubImage_ShouldRecognizeSubimageAfterResizing. It's not stable and could pass or not pass randomly for small image(related to resizing in thresholder).

**Comment by ws233** [comment]
Overall, I think that approach is better. We have one image less in the memory at the moment.

**Comment by BamX** [comment]
May be there should be something special for ColorSpace or BitmapInfo at context initialization in the new realization of ```pixFromImage```. 
And there rotated pages orientation tests needed. I'll add them soon.
But still don't know what to do with SimpleImage_SubImage_ShouldRecognizeSubimageAfterResizing.

**Comment by ws233** [comment]
That's what I wanted to ask. You code draws an image in 32bpp? Even if the inoput image is 8bpp?

And can we help with this test? Can you explain what the issue is?

**Comment by BamX** [comment]
No, it uses original bitmap info.
Test I mentioned is just for check that rotated image will be rotated back in pixFromImage.

**Comment by ws233** [comment]
>> There was one broken test: SimpleImage_SubImage_ShouldRecognizeSubimageAfterResizing. It's not stable and could pass or not pass randomly for small image(related to resizing in thresholder).

I think that's due to float type restrictions. I mean rounding and precision. Perhaps, we should return back to the absolute rect coordinates instead of relative ones? Could we just scale the original recognition rect, if the image was scaled in the delegate method? That should be much more stable and does not depend on the rounding.

**Comment by kevincon** [comment]
I'm closing this pull request and continuing it in #160.

**Pull request closed without merging**
