### PR TITLE
Increasing code coverage. Test 8 bit images.

### PR DESCRIPTION
**Pull request by ws233**

### CODE REVIEW

**Comment by ws233** [comment]
I will add more here soon. Pls, don't merge yet.

**Comment by ws233** [comment]
I've added more tests coverring recognizedPDFForImages funxtion using.
But unfortunatelly I don't know how to cover those 'return nil;' lines from that function.
Any ideas?

**Comment by kevincon** [comment]
Hmm, yeah I'm not sure they're reachable given our protections in other places in the code. I would be okay with marking them to be excluded by the testing coverage. It looks like Coveralls supports lcov's line exclusion marker `LCOV_EXCL_LINE` (https://github.com/eddyxu/cpp-coveralls/blob/a98de58fbe68b9eb77bb299c7236c582215e0fa6/cpp_coveralls/coverage.py#L197). So for example, you could add a comment at the end of the lines like this:

``` Objective-C
return nil; // LCOV_EXCL_LINE
```

What do you think?

**Comment by ws233** [comment]
Hm... Let me try this.

**Comment by ws233** [comment]
I've found an error in our initialization code and the test, which I wrote to cover that code.
So I've fixed both in the last commit.

**Comment by ws233** [comment]
and // LCOV_EXCL_LINE doesn't work in catch block due to unknown reason.

**Comment by ws233** [comment]
Seems I've finished with the code coverage.

**Comment by kevincon** [comment]
Nice job! :) Ready for me to merge this PR?

**Comment by ws233** [comment]
Yes, I am. Could you merge it, pls, and close related ticket?

**Pull request merged**
