### PR TITLE
macOS support

### PR DESCRIPTION
**Pull request by hamchapman**
Here's a list of the the high level changes:

* Added macOS support
* Updated version of tesseract to 4.1.0-rc1 (using roughly the latest HEAD)
* Leptonica is now included as a git submodule
* A fork of libtiff-ios is being used as part of the macOS support: https://github.com/hamchapman/libtiff-ios
* Introduced a new Tests-macOS project, which almost entirely reflects that Tests-iOS one
  * The two Tests-* projects share almost all of their code, which lives in the Tests directory

### CODE REVIEW

**Comment by hamchapman** [comment]
@gali8 shall I merge this?

At least anecdotally people seem to be using it with success: #379

**Comment by arrrrny** [comment]
I just built from your branch and tried running Example Swift Test on my iPhone 7 Plus. Getting this error while opening the app, it doesn't open. any idea? Have you tried this on iphone? it works fine on simulator.

**Comment by hamchapman** [comment]
What's the error you're getting?

**Comment by arrrrny** [comment]
Screen Shot 2019-10-08 at 9 26 16 PM

**Comment by hamchapman** [comment]
@arrrrny try again now

**Comment by arrrrny** [comment]
Awesome! Now app opens on my iPhone, I just tried taking a photo of a text. just nothing happens, gets back to home screen of the app. It does not show anything either, in the debug console.

**Comment by arrrrny** [comment]
When I try to build the framework, I am getting below error.
ld: library not found for -lpng

Ld /Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Intermediates.noindex/TesseractOCR.build/Debug-iphoneos/TesseractOCR.build/Objects-normal/arm64/Binary/TesseractOCR normal arm64 (in target 'TesseractOCR' from project 'TesseractOCR')
    cd /Users/arrrrny/Developer/TesseractOCR
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -L/Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Products/Debug-iphoneos -F/Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Products/Debug-iphoneos -filelist /Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Intermediates.noindex/TesseractOCR.build/Debug-iphoneos/TesseractOCR.build/Objects-normal/arm64/TesseractOCR.LinkFileList -install_name @rpath/TesseractOCR.framework/TesseractOCR -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Intermediates.noindex/TesseractOCR.build/Debug-iphoneos/TesseractOCR.build/Objects-normal/arm64/TesseractOCR_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -**ObjC -lc++ -lc++ -lpng -llept -ltesseract -ljpeg -ltiff -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker** /Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Intermediates.noindex/TesseractOCR.build/Debug-iphoneos/TesseractOCR.build/Objects-normal/arm64/TesseractOCR_dependency_info.dat -o /Users/arrrrny/Library/Developer/Xcode/DerivedData/TesseractOCR-ehrmgaizemgpkbeeqhpnpvroljyj/Build/Intermediates.noindex/TesseractOCR.build/Debug-iphoneos/TesseractOCR.build/Objects-normal/arm64/Binary/TesseractOCR

**ld: library not found for -lpng**

**Comment by WeiWenTaoApple** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Pull request closed without merging**
