### PR TITLE
Fix library makefile and xcode 10 build

### PR DESCRIPTION
**Pull request by galbraithjoseph**
This is the smallest change I could come up with to get the Makefile building the libraries again and doing so with xCode 10.
* Downloading of image libraries from libtiff-ios was failing.  Updated to most recent master for libtiff-ios submodule
* leptonica did not build with xCode 10 because of usage of system().  This was true even for the most recent release of leptonica (though the problem is fixed in master for leptonica) . Here, I elected to hack-patch the current version of leptonica to simply bypass any use of system() and fail with ENOENT instead. (I don't believe we should be using the functions that needed system anyway.)
* Remove unneeded -lstdc++ from the podspec to resolve problems with incorrectly linking libstdc++ on the simulator.

### CODE REVIEW

**Comment by jkufver** [comment]
Hi Joseph, this patch is exactly what I need.

Will it ever be incorporated in the gali8's master branch? Is that repo still maintained?

Should I start using your branch instead? Will you merge _build-fix_ into your _master_?

Best regards Jens Kufver

I'm using Cocoapods pods/TesseractOCRiOS right now (not updated since 2015!?!). Maybe I should use git submodule instead in this case...

**Comment by gali8** [comment]
merged

**Comment by jkufver** [comment]
Wow... that was fast.

**Comment by gali8** [comment]
@galbraithjoseph travis-ci is failing, please fix. Only later i can merge. I'm sorry, i must revert now.

**Comment by galbraithjoseph** [comment]
Unfortunately, as far as I can tell, travis-ci was failing before the fix
too.  I made a couple of attempts but ran out of time for much else (I
might have some time to spend on next week, but no promises...)

**Comment by gali8** [comment]
Ok, keep in touch!

**Pull request merged**
