### PR TITLE
Remove copyFilesFromResources parameter from initializer

### PR DESCRIPTION
**Pull request by PatrickNLT**
WIP for #170

### CODE REVIEW

**Comment by PatrickNLT** [comment]
There is no test for now for the case when there is no tessdata directory in the application bundle: if anyone knows how to mock this, please comment.

**Comment by ws233** [comment]
Pls, take a look here:
https://github.com/kiwi-bdd/Kiwi/wiki/Mocks-and-Stubs

**Comment by ws233** [comment]
@PatrickNLT, one more thing.
It seems that there are two instances of very similar code in tests:
1. copyDataToCustomDirectory and moveTessdataToCachesDirectoryIfNecessary
2. cleanCustomTessdataFolder and cleanTessdataFolder.
Could you tale carefully on that code and change it so there is no code duplication?

**Comment by ws233** [comment]
I've fixed my own concerns in #189.
Pls, review.

**Comment by ws233** [comment]
> There is no test for now for the case when there is no tessdata directory in the application bundle: if anyone knows how to mock this, please comment.

There is a case in InitializationTests.m at line 358, which does exactly what is requested.

        it(@"Should return nil if contentsOfDirectoryAtPath fails", ^{
            checkInitializationWithFailedSelectorReturnValueAndCount(@selector(contentsOfDirectoryAtPath:error:), nil, 2);
            cleanTessdataFolderAtPath(cachesTessDataPath);
        });

So it seems the issue can be closed, if there is no more concerns about it, @kevincon.

**Pull request merged**
