### PR TITLE
Missing 'preprocessedImageForTesseract:sourceImage:' delegate forwarding

### PR DESCRIPTION
**Pull request by mgratzer**

### CODE REVIEW

**Comment by kevincon** [comment]
Thanks for this pull request! Since our unit tests didn't catch that the delegate function was missing in `G8RecognitionOperation`, could you also add a unit test that covers this?

**Comment by mgratzer** [comment]
I adopted the existing approach checking for the operation callback blocks and added assertions for all forwarded callbacks using the delegate pattern inside `G8RecognitionTestsHelper`.

**Comment by ws233** [comment]
@kevincon, we have lost test coverage badge for every PR?
I don't see them anymore.

**Comment by kevincon** [comment]
@mgratzer Thanks so much! Merging and closing now...

@ws233 I'm not sure, I think @gali8 might need to re-authorize coveralls or double-check the repo's settings at coveralls.io. I'll create a new issue for this task for him.

**Comment by ws233** [comment]
There was 1 uncovered line in this patch.

@mgratzer, since we are trying to achive 100% code test coverage,
Could you add tests to cover that 1 missed line from your patch?

**Pull request merged**
