### PR TITLE
implement function to retrieve hierarchical recognized blocks

### PR DESCRIPTION
**Pull request by juergenm**
I added a function to retrieve hierarchical structured `G8HierarchicalRecognizedBlock`'s so that it is possible to move down from a paragraph to a textline and from a textline to a word etc.

I extended the `G8RecognizedBlock` by a property `childBlocks` which contains an Array of blocks of the next lower iterator level. 

In addition I added some more information to words (`isFromDict`, `isNumberic`, `isBold`, `isItalic`) and characters (`characterChoices`) see `G8HierarchicalRecognizedBlock`.

### CODE REVIEW

**Comment by ws233** [comment]
@juergenm, thanks for helping us making TesseractOCR-iOS better!
But TesseractOCR-iOS is 100% code covered framework.
So I cannot merge your code without unit tests covered all the lines of your code.
Would you mind writing unit tests for your code?

**Comment by juergenm** [comment]
I added unit tests, but the Travis CI doesn't build. Could you help me?

**Comment by ws233** [comment]
@juergenm, thx for you help!
I've found the reason of the issue.
I'm preparing the patch.

**Comment by ws233** [comment]
@juergenm, I've fixed an issue with broken #241.
Pls, rebase your PR ontop of the #241.
Than I'll try to understand what's wrong with coveralls.
Thank's!

**Comment by juergenm** [comment]
closed by #246

**Pull request closed without merging**
