### PR TITLE
Carthage and Bitcode Support

### PR DESCRIPTION
**Pull request by eduardo22i**
Pull requests gives an update to the framework. It enables modern iOS development technologies.

- Carthage Support
- Bitcode Enabled 
- Swift 4 Example

I dropped iOS 8 support.

### CODE REVIEW

**Comment by zsajjad** [comment]
What's stopping this PR to get merged? @eduardo22i can you please resolve these conflicts that will be so nice of you. 😄

**Comment by gali8** [comment]
please solve conclicts

**Comment by eduardo22i** [comment]
conflicts solved @zsajjad @gali8 :)

**Comment by juergenm** [comment]
@eduardo22i Why did you remove the function `recognizedHierarchicalBlocksByIteratorLevel:(G8PageIteratorLevel)pageIteratorLevel` from `G8Tesseract.h`? Can this function be added again?

**Comment by eduardo22i** [comment]
Good catch, it was my mistake. I'll add it again!

**Comment by eduardo22i** [comment]
Good catch @juergenm, it was my mistake. I'll add it again!

**Pull request merged**
