### PR TITLE
G8RecognizedBlock unit tests

### PR DESCRIPTION
**Pull request by ws233**
1. Some unit tests for recognized block class.
2. That unit tests helps to find an issue in a isEqual and hash functions.

### CODE REVIEW

**Comment by ws233** [comment]
Let's move discussion here.
What do you think about this code?
It will return immediately after any of the copnfitions is failed. That should wrong much faster, while searching in collections.

**Comment by BamX** [comment]
Looks good. Why you not implemented *not-empty* block tests? Any difficulties?

**Comment by ws233** [comment]
No. Will do soon. Just decided to show the issue before to make sure there is no concerns about it and I do understand this correctly.

**Comment by kevincon** [comment]
Looks good to me so far.

**Comment by ws233** [comment]
Just made a rebase to respect tonights merges in this PR.

**Comment by ws233** [comment]
on more rebase

**Comment by ws233** [comment]
Merge?

**Comment by kevincon** [comment]
Sure, I'll merge and close it now.

**Pull request merged**
